"""set id as nullable and remove unnessary index

Revision ID: 82c4400aa3e4
Revises: 2a546047b68a
Create Date: 2024-11-22 02:59:00.529388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c4400aa3e4'
down_revision: Union[str, None] = '2a546047b68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_categories', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_ingredient_categories_name', table_name='ingredient_categories')
    op.create_unique_constraint(None, 'ingredient_categories', ['name'])
    op.alter_column('ingredient_recipe_associations', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ingredients', 'ingredient_category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ingredients', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_ingredients_brand', table_name='ingredients')
    op.drop_index('ix_ingredients_name', table_name='ingredients')
    op.create_unique_constraint(None, 'ingredients', ['name'])
    op.alter_column('recipe_categories', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_recipe_categories_name', table_name='recipe_categories')
    op.create_unique_constraint(None, 'recipe_categories', ['name'])
    op.alter_column('recipe_origins', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_recipe_origins_name', table_name='recipe_origins')
    op.create_unique_constraint(None, 'recipe_origins', ['name'])
    op.alter_column('recipe_tags', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_recipe_tags_name', table_name='recipe_tags')
    op.create_unique_constraint(None, 'recipe_tags', ['name'])
    op.alter_column('recipes', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_recipes_author', table_name='recipes')
    op.drop_index('ix_recipes_cooking_time', table_name='recipes')
    op.drop_index('ix_recipes_instructions', table_name='recipes')
    op.drop_index('ix_recipes_name', table_name='recipes')
    op.drop_index('ix_recipes_serving', table_name='recipes')
    op.create_unique_constraint(None, 'recipes', ['name'])
    op.drop_column('recipes', 'author')
    op.alter_column('uoms', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_uoms_name', table_name='uoms')
    op.drop_index('ix_uoms_unit', table_name='uoms')
    op.create_unique_constraint(None, 'uoms', ['unit'])
    op.create_unique_constraint(None, 'uoms', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uoms', type_='unique')
    op.drop_constraint(None, 'uoms', type_='unique')
    op.create_index('ix_uoms_unit', 'uoms', ['unit'], unique=True)
    op.create_index('ix_uoms_name', 'uoms', ['name'], unique=True)
    op.alter_column('uoms', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('recipes', sa.Column('author', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipes', type_='unique')
    op.create_index('ix_recipes_serving', 'recipes', ['serving'], unique=False)
    op.create_index('ix_recipes_name', 'recipes', ['name'], unique=True)
    op.create_index('ix_recipes_instructions', 'recipes', ['instructions'], unique=False)
    op.create_index('ix_recipes_cooking_time', 'recipes', ['cooking_time'], unique=False)
    op.create_index('ix_recipes_author', 'recipes', ['author'], unique=False)
    op.alter_column('recipes', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'recipe_tags', type_='unique')
    op.create_index('ix_recipe_tags_name', 'recipe_tags', ['name'], unique=True)
    op.alter_column('recipe_tags', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'recipe_origins', type_='unique')
    op.create_index('ix_recipe_origins_name', 'recipe_origins', ['name'], unique=True)
    op.alter_column('recipe_origins', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'recipe_categories', type_='unique')
    op.create_index('ix_recipe_categories_name', 'recipe_categories', ['name'], unique=True)
    op.alter_column('recipe_categories', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'ingredients', type_='unique')
    op.create_index('ix_ingredients_name', 'ingredients', ['name'], unique=True)
    op.create_index('ix_ingredients_brand', 'ingredients', ['brand'], unique=False)
    op.alter_column('ingredients', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ingredients', 'ingredient_category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('ingredient_recipe_associations', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'ingredient_categories', type_='unique')
    op.create_index('ix_ingredient_categories_name', 'ingredient_categories', ['name'], unique=True)
    op.alter_column('ingredient_categories', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
