"""edit assocta

Revision ID: 5824a84f2f02
Revises: 2b69c305571b
Create Date: 2024-01-22 22:15:57.067950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5824a84f2f02'
down_revision: Union[str, None] = '2b69c305571b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_recipe_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], ),
    sa.PrimaryKeyConstraint('id', 'ingredient_id', 'recipe_id')
    )
    op.create_index(op.f('ix_ingredient_recipe_association_id'), 'ingredient_recipe_association', ['id'], unique=False)
    op.drop_table('ingredient_recipe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_recipe',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='ingredient_recipe_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='ingredient_recipe_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], name='ingredient_recipe_uom_id_fkey')
    )
    op.drop_index(op.f('ix_ingredient_recipe_association_id'), table_name='ingredient_recipe_association')
    op.drop_table('ingredient_recipe_association')
    # ### end Alembic commands ###
