"""initial

Revision ID: 86bd8c457ff7
Revises: 
Create Date: 2024-01-17 03:07:05.093450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bd8c457ff7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_category',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_category_id'), 'ingredient_category', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_category_name'), 'ingredient_category', ['name'], unique=True)
    op.create_table('recipe_category',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_category_id'), 'recipe_category', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_category_name'), 'recipe_category', ['name'], unique=True)
    op.create_table('recipe_origin',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_origin_id'), 'recipe_origin', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_origin_name'), 'recipe_origin', ['name'], unique=True)
    op.create_table('recipe_tag',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_tag_id'), 'recipe_tag', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_tag_name'), 'recipe_tag', ['name'], unique=True)
    op.create_table('uom',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uom_id'), 'uom', ['id'], unique=False)
    op.create_index(op.f('ix_uom_name'), 'uom', ['name'], unique=True)
    op.create_index(op.f('ix_uom_unit'), 'uom', ['unit'], unique=True)
    op.create_table('ingredient',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('is_essential', sa.Boolean(), nullable=True),
    sa.Column('ingredient_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_category_id'], ['ingredient_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_brand'), 'ingredient', ['brand'], unique=False)
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=True)
    op.create_table('recipe',
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serving', sa.Integer(), nullable=True),
    sa.Column('cooking_time', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('instuctions', sa.Text(), nullable=True),
    sa.Column('recipe_category_id', sa.Integer(), nullable=False),
    sa.Column('recipe_origin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_category_id'], ['recipe_category.id'], ),
    sa.ForeignKeyConstraint(['recipe_origin_id'], ['recipe_origin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_author'), 'recipe', ['author'], unique=False)
    op.create_index(op.f('ix_recipe_cooking_time'), 'recipe', ['cooking_time'], unique=False)
    op.create_index(op.f('ix_recipe_id'), 'recipe', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_instuctions'), 'recipe', ['instuctions'], unique=False)
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=True)
    op.create_index(op.f('ix_recipe_serving'), 'recipe', ['serving'], unique=False)
    op.create_table('ingredient_recipe_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], ),
    sa.PrimaryKeyConstraint('id', 'ingredient_id', 'recipe_id')
    )
    op.create_index(op.f('ix_ingredient_recipe_association_id'), 'ingredient_recipe_association', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_recipe_association_id'), table_name='ingredient_recipe_association')
    op.drop_table('ingredient_recipe_association')
    op.drop_index(op.f('ix_recipe_serving'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_instuctions'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_id'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_cooking_time'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_author'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_brand'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_index(op.f('ix_uom_unit'), table_name='uom')
    op.drop_index(op.f('ix_uom_name'), table_name='uom')
    op.drop_index(op.f('ix_uom_id'), table_name='uom')
    op.drop_table('uom')
    op.drop_index(op.f('ix_recipe_tag_name'), table_name='recipe_tag')
    op.drop_index(op.f('ix_recipe_tag_id'), table_name='recipe_tag')
    op.drop_table('recipe_tag')
    op.drop_index(op.f('ix_recipe_origin_name'), table_name='recipe_origin')
    op.drop_index(op.f('ix_recipe_origin_id'), table_name='recipe_origin')
    op.drop_table('recipe_origin')
    op.drop_index(op.f('ix_recipe_category_name'), table_name='recipe_category')
    op.drop_index(op.f('ix_recipe_category_id'), table_name='recipe_category')
    op.drop_table('recipe_category')
    op.drop_index(op.f('ix_ingredient_category_name'), table_name='ingredient_category')
    op.drop_index(op.f('ix_ingredient_category_id'), table_name='ingredient_category')
    op.drop_table('ingredient_category')
    # ### end Alembic commands ###
