"""edit assoctaaaaa

Revision ID: 8dcf1d5ad65c
Revises: 4655d00a2077
Create Date: 2024-01-22 22:41:14.016924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dcf1d5ad65c'
down_revision: Union[str, None] = '4655d00a2077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
