"""fix primary key

Revision ID: b0227597155b
Revises: e26dcfefd72c
Create Date: 2024-01-22 02:21:57.446563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0227597155b'
down_revision: Union[str, None] = 'e26dcfefd72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_recipe_association_pkey', 'ingredient_recipe_association', type_='primary')
    op.create_primary_key('ingredient_recipe_association_pkey', 'ingredient_recipe_association', columns=['recipe_id', 'ingredient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
