"""modify_ingredient_relationship

Revision ID: d608e7ca5925
Revises: 86bd8c457ff7
Create Date: 2024-01-17 04:35:17.791489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd608e7ca5925'
down_revision: Union[str, None] = '86bd8c457ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
