"""edit assoc

Revision ID: e4769974f703
Revises: b0227597155b
Create Date: 2024-01-22 21:36:16.933585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4769974f703'
down_revision: Union[str, None] = 'b0227597155b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('uom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], )
    )
    op.drop_index('ix_ingredient_recipe_association_id', table_name='ingredient_recipe_association')
    op.drop_table('ingredient_recipe_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_recipe_association',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uom_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='ingredient_recipe_association_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='ingredient_recipe_association_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.id'], name='ingredient_recipe_association_uom_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'ingredient_id', 'recipe_id', name='ingredient_recipe_association_pkey')
    )
    op.create_index('ix_ingredient_recipe_association_id', 'ingredient_recipe_association', ['id'], unique=False)
    op.drop_table('ingredient_recipe')
    # ### end Alembic commands ###
