"""adjust recipe tag

Revision ID: e93ecf0d49f8
Revises: b078cb8bd845
Create Date: 2024-01-17 04:58:31.064379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93ecf0d49f8'
down_revision: Union[str, None] = 'b078cb8bd845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('recipe_tag_id', sa.Integer(), nullable=True))
    op.alter_column('recipe', 'recipe_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipe', 'recipe_origin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'recipe', 'recipe_tag', ['recipe_tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.alter_column('recipe', 'recipe_origin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipe', 'recipe_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recipe', 'recipe_tag_id')
    # ### end Alembic commands ###
